#!/bin/bash
#So you thought looking at the source code would help you win?
#Well, maybe!
#Can you figure out how to win this game?
#Also, tweet me @realtalishaw for hints!

echo -e '#!/bin/bash' > .print && echo -e 'head -n $1 .gametext | tail -n +$1 | pv -qL 30' >> .print && chmod u+x .print && p=./.print 
export p

clear
echo "Welcome to the game! We are going to install some libraries needed. Make sure to type Y when prompted!"
echo -e "When questions are asked in the game you may answer y or Y for yes and n or N for no"
echo "Good luck, and have fun!"
sleep 5s
clear

#sudo apt-get update
#sudo apt-get install figlet
#sudo apt-get install toilet
#sudo apt-get install pv 
#clear

figlet -f future -c "Holberton School of Witchcraft and Wizardry" 
sleep 1s
echo  "Book 1: The Programmer's Stone" | pv -qL 15
clear
 
echo -e "What shall we call you?" | pv -qL 15
read -r name
sed -i "s/player/${name}/g" .gametext
export name
clear
 
$p 2
$p 3
read answer

if [ "$answer" = "y" ]; then
    $p 5
else 
    $p 4 && clear && rm .print &&  rm start_game && rm .gametext && figlet -f mono12 -c  "GAME OVER!"
fi

$p 7
$p 8
$p 9
$p 10
read answer

if [ "$answer" = "y" ]; then
    $p 11 && sed -n '95,112p' .gametext > school_supplies
else
    echo "IDK what you want me to do then?"
fi

$p 13
read answer


if [ "$answer" = "cat school_supplies" ]; then
    cat school_supplies && echo && sleep 3s  
else
    echo "Not quite! Hint: How do you display the contents of a file?"
fi

$p 14
$p 15

echo -e '#/bin/bash' > .siliconValley
chmod u+x .siliconValley
echo -e 'p=./.print'  >> .siliconValley
echo -e '$p 16\n$p 17\n$p 18' >> .siliconValley
echo && head -n 115 .gametext | tail -n +115 >> .siliconValley

