#!/bin/bash
#So you thought looking at the source code would help you win?
#Well, maybe!
#Can you figure out how to win this game?
#Also, tweet me @realtalishaw for hints!

echo -e '#!/bin/bash' > .print && echo -e 'head -n $1 .gametext | tail -n +$1 | pv -qL 15' >> .print && chmod u+x .print && p=./.print 

clear
echo "Welcome to the game! We are going to install some libraries needed. Make sure to type Y when prompted!"
echo -e "When questions are asked in the game you may answer y or Y for yes and n or N for no"
echo "Good luck, and have fun!"
sleep 5s
clear

#sudo apt-get update
#sudo apt-get install figlet
#sudo apt-get install toilet
#sudo apt-get install pv 
#clear

figlet -f future -c "Holberton School of Witchcraft and Wizardry" 
sleep 1s
echo  "Book 1: The Programmer's Stone" | pv -qL 15
clear
 
echo -e "What shall we call you?" | pv -qL 15
read -r player
export player
clear
 
$p 2
$p 3
read answer

if [ "$answer" = "y" ]; then
    $p 5
else 
    $p 4 && cd &&  rm -r holbertonschool_witchcraft_wizardry
fi


